### ISSUE TITLE
[Enquiry] - Rune Contest 

### ISSUE THREAD

**Issue by simonjulianl** [indocomsoft/CS1101S-indocomsoft#1]
Hi, my name is  Simon and currently Y2 CS teaching 1101S

I stumble upon this repo and am amazed by the rune contest submissions but didn't get the ways how the rune can be created (the one with starry night, prof martin henz face, etc). I understand it has been a very long time since you took this mod but do you if you share some insights on how to generate those runes ?

Regards,
Simon

**Comment by indocomsoft** [comment]
Hey Simon, I wrote this script to generate them from a png input image: https://github.com/indocomsoft/png-to-thesource

**Comment by simonjulianl** [comment]
I see thank you for the prompt reply!
